### PR TITLE
Upgrade bitvec

### LINKED ISSUE #70: `bitvec` v1.0
Would be nice to get a `bitvec` bump now that 1.0 is out:

https://crates.io/crates/bitvec/1.0.0

### PR DESCRIPTION
**Pull request by koivunej**
Fixes #70. Upgrades MSRV from 1.51 to 1.56, matching bitvec's, upgrades bitvec to "1".

Follow-up to #72, which is hopefully merged and a patch version released first. There shouldn't be any major conflicts, but the workflow will need to be fixed for ~the nightly doc lint job's rust version (#72 changed it to 1.51, needs to be 1.56 now)~ .. ended up doing that in this branch as well, latest nightly [rustdoc has some issues](https://github.com/eqlabs/ff/runs/4964639285?check_suite_focus=true#step:5:22).

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Any chance this could be merged? I have a lot of duplicates of bitvec in my dependency tree due to this currently.

**Review by str4d — APPROVED** [review]
utACK, looks exactly like what I'd planned to do 😄

**Comment by str4d** [comment]
Merging this will commit the main branch to an 0.12 release, so I'm going to hold off merging this until we're definitely on that train. If @koivunej can fix #72 before then, we can perhaps get a point release out with that.

**Comment by koivunej** [comment]
> If koivunej can fix https://github.com/zkcrypto/ff/pull/72 before then, we can perhaps get a point release out with that.

This would sound excellent and help anyone trying to use the `ff` as different bitvec versions are still being depended on in the wild.

**Review by ebfull — APPROVED** [review]

**Pull request merged**
