### PR TITLE
Add ?Sized to RngCore trait bounds

### LINKED ISSUE #13: RngCore should be used with ?Sized

### PR DESCRIPTION
**Pull request by kigawas**
Closes #13.

### CODE REVIEW

**Comment by str4d** [comment]
Could you please squash these commits together?

**Comment by kigawas** [comment]
I don't see any necessity to manually squash them, you can just squash merge

**Comment by str4d** [comment]
Oh right, I forgot that option exists in the GitHub UI (I literally never use it).

**Comment by kigawas** [comment]
> PR contents LGTM once squashed. I still need to confirm that this is a backwards-compatible change.

Have you confirmed it? `?Sized` should be more permissive here

**Comment by str4d** [comment]
I'm sufficiently convinced this is backwards-compatible.

**Comment by dignifiedquire** [comment]
It is not, this is breaking various builds of ours :(

**Comment by kigawas** [comment]
@str4d 

Can you check this https://github.com/zkcrypto/pairing/pull/108 ?

**Pull request merged**
